from app.models import db, Crypto

# prices from 06/09/2022 for defaults
# Adds a demo user, you can add other users here if you want
def seed_crypto():

  btc = Crypto(name="Bitcoin", symbol="btc", price=30087)
  db.session.add(btc)
  eth = Crypto(name="Ethereum", symbol="eth", price=1788.15)
  db.session.add(eth)
  usdt = Crypto(name="Tether", symbol="usdt", price=0.99964)
  db.session.add(usdt)
  usdc = Crypto(name="USD Coin", symbol="usdc", price=1.001)
  db.session.add(usdc)
  bnb = Crypto(name="BNB", symbol="bnb", price=289.66)
  db.session.add(bnb)
  ada = Crypto(name="Cardano", symbol="ada", price=0.632445)
  db.session.add(ada)
  xrp = Crypto(name="XRP", symbol="xrp", price=0.399837)
  db.session.add(xrp)
  busd = Crypto(name="Binance USD", symbol="busd", price=1.001)
  db.session.add(busd)
  sol = Crypto(name="Solana", symbol="sol", price=39.97)
  db.session.add(sol)
  doge = Crypto(name="Dogecoin", symbol="doge", price=0.079842)
  db.session.add(doge)
  dot = Crypto(name="Polkadot", symbol="dot", price=9.21)
  db.session.add(dot)
  wbtc = Crypto(name="Wrapped Bitcoin", symbol="wbtc", price=30053)
  db.session.add(wbtc)
  trx = Crypto(name="TRON", symbol="trx", price=0.080867)
  db.session.add(trx)
  steth = Crypto(name="Lido Staked Ether", symbol="steth", price=1737.76)
  db.session.add(steth)
  avax = Crypto(name="Avalanche", symbol="avax", price=24.36)
  db.session.add(avax)
  dai = Crypto(name="Dai", symbol="dai", price=1)
  db.session.add(dai)
  shib = Crypto(name="Shiba Inu", symbol="shib", price=0.00001055)
  db.session.add(shib)
  leo = Crypto(name="LEO Token", symbol="leo", price=5.42)
  db.session.add(leo)
  cro = Crypto(name="Cronos", symbol="cro", price=0.174145)
  db.session.add(cro)
  matic = Crypto(name="Polygon", symbol="matic", price=0.630697)
  db.session.add(matic)
  link = Crypto(name="Chainlink", symbol="link", price=9.24)
  db.session.add(link)
  ltc = Crypto(name="Litecoin", symbol="ltc", price=60.03)
  db.session.add(ltc)
  ftt = Crypto(name="FTX", symbol="ftt", price=28.51)
  db.session.add(ftt)
  near = Crypto(name="NEAR Protocol", symbol="near", price=5.07)
  db.session.add(near)
  xlm = Crypto(name="Stellar", symbol="xlm", price=0.139332)
  db.session.add(xlm)
  xcn = Crypto(name="Chain", symbol="xcn", price=0.16056)
  db.session.add(xcn)
  xmr = Crypto(name="Monero", symbol="xmr", price=184.75)
  db.session.add(xmr)
  bch = Crypto(name="Bitcoin Cash", symbol="bch", price=175.23)
  db.session.add(bch)
  okb = Crypto(name="OKB", symbol="okb", price=11.33)
  db.session.add(okb)
  etc = Crypto(name="Ethereum Classic", symbol="etc", price=21.17)
  db.session.add(etc)
  algo = Crypto(name="Algorand", symbol="algo", price=0.402702)
  db.session.add(algo)
  atom = Crypto(name="Cosmos Hub", symbol="atom", price=8.77)
  db.session.add(atom)
  flow = Crypto(name="Flow", symbol="flow", price=2.39)
  db.session.add(flow)
  uni = Crypto(name="Uniswap", symbol="uni", price=5.19)
  db.session.add(uni)
  vet = Crypto(name="VeChain", symbol="vet", price=0.03187564)
  db.session.add(vet)
  xtz = Crypto(name="Tezos", symbol="xtz", price=2.21)
  db.session.add(xtz)
  tfuel = Crypto(name="Theta Fuel", symbol="tfuel", price=0.062995)
  db.session.add(tfuel)
  hbar = Crypto(name="Hedera", symbol="hbar", price=0.086812)
  db.session.add(hbar)
  ape = Crypto(name="ApeCoin", symbol="ape", price=5.73)
  db.session.add(ape)
  sand = Crypto(name="The Sandbox", symbol="sand", price=1.29)
  db.session.add(sand)
  kcs = Crypto(name="KuCoin", symbol="kcs", price=15.94)
  db.session.add(kcs)
  fil = Crypto(name="Filecoin", symbol="fil", price=7.21)
  db.session.add(fil)
  axs = Crypto(name="Axie Infinity", symbol="axs", price=19.45)
  db.session.add(axs)
  icp = Crypto(name="Internet Computer", symbol="icp", price=6.41)
  db.session.add(icp)
  frax = Crypto(name="Frax", symbol="frax", price=0.998604)
  db.session.add(frax)
  mana = Crypto(name="Decentraland", symbol="mana", price=0.973332)
  db.session.add(mana)
  theta = Crypto(name="Theta Network", symbol="theta", price=1.41)
  db.session.add(theta)
  egld = Crypto(name="Elrond", symbol="egld", price=61.64)
  db.session.add(egld)
  ceth = Crypto(name="cETH", symbol="ceth", price=35.86)
  db.session.add(ceth)
  aave = Crypto(name="Aave", symbol="aave", price=96.03)
  db.session.add(aave)
  eos = Crypto(name="EOS", symbol="eos", price=1.24)
  db.session.add(eos)
  tusd = Crypto(name="TrueUSD", symbol="tusd", price=1.001)
  db.session.add(tusd)
  hnt = Crypto(name="Helium", symbol="hnt", price=11.78)
  db.session.add(hnt)
  hbtc = Crypto(name="Huobi BTC", symbol="hbtc", price=30312)
  db.session.add(hbtc)
  cusdc = Crypto(name="cUSDC", symbol="cusdc", price=0.02264103)
  db.session.add(cusdc)
  zec = Crypto(name="Zcash", symbol="zec", price=91.36)
  db.session.add(zec)
  dfi = Crypto(name="DeFiChain", symbol="dfi", price=2.04)
  db.session.add(dfi)
  grt = Crypto(name="The Graph", symbol="grt", price=0.147144)
  db.session.add(grt)
  ht = Crypto(name="Huobi", symbol="ht", price=6.91)
  db.session.add(ht)
  bsv = Crypto(name="Bitcoin SV", symbol="bsv", price=55.7)
  db.session.add(bsv)
  klay = Crypto(name="Klaytn", symbol="klay", price=0.366637)
  db.session.add(klay)
  mkr = Crypto(name="Maker", symbol="mkr", price=1133.1)
  db.session.add(mkr)
  xec = Crypto(name="eCash", symbol="xec", price=0.00005153)
  db.session.add(xec)
  btt = Crypto(name="BitTorrent", symbol="btt", price=0.00000105)
  db.session.add(btt)
  miota = Crypto(name="IOTA", symbol="miota", price=0.344624)
  db.session.add(miota)
  usdp = Crypto(name="Pax Dollar", symbol="usdp", price=1.001)
  db.session.add(usdp)
  ftm = Crypto(name="Fantom", symbol="ftm", price=0.335394)
  db.session.add(ftm)
  qnt = Crypto(name="Quant", symbol="qnt", price=63.22)
  db.session.add(qnt)
  neo = Crypto(name="NEO", symbol="neo", price=12.01)
  db.session.add(neo)
  rune = Crypto(name="THORChain", symbol="rune", price=2.81)
  db.session.add(rune)
  gt = Crypto(name="Gate", symbol="gt", price=5.49)
  db.session.add(gt)
  usdn = Crypto(name="Neutrino USD", symbol="usdn", price=0.966635)
  db.session.add(usdn)
  xrd = Crypto(name="Radix", symbol="xrd", price=0.080514)
  db.session.add(xrd)
  waves = Crypto(name="Waves", symbol="waves", price=7.84)
  db.session.add(waves)
  lunc = Crypto(name="Terra Luna Classic", symbol="lunc", price=0.00007609)
  db.session.add(lunc)
  zil = Crypto(name="Zilliqa", symbol="zil", price=0.04890979)
  db.session.add(zil)
  usdd = Crypto(name="USDD", symbol="usdd", price=0.999557)
  db.session.add(usdd)
  cdai = Crypto(name="cDAI", symbol="cdai", price=0.02202545)
  db.session.add(cdai)
  nexo = Crypto(name="NEXO", symbol="nexo", price=1.21)
  db.session.add(nexo)
  ar = Crypto(name="Arweave", symbol="ar", price=13.25)
  db.session.add(ar)
  cake = Crypto(name="PancakeSwap", symbol="cake", price=4.38)
  db.session.add(cake)
  lrc = Crypto(name="Loopring", symbol="lrc", price=0.512513)
  db.session.add(lrc)
  chz = Crypto(name="Chiliz", symbol="chz", price=0.119242)
  db.session.add(chz)
  dash = Crypto(name="Dash", symbol="dash", price=57.71)
  db.session.add(dash)
  paxg = Crypto(name="PAX Gold", symbol="paxg", price=1847.01)
  db.session.add(paxg)
  ksm = Crypto(name="Kusama", symbol="ksm", price=66.46)
  db.session.add(ksm)
  snx = Crypto(name="Synthetix Network", symbol="snx", price=2.69)
  db.session.add(snx)
  bit = Crypto(name="BitDAO", symbol="bit", price=0.543868)
  db.session.add(bit)
  gmt = Crypto(name="STEPN", symbol="gmt", price=0.989039)
  db.session.add(gmt)
  bat = Crypto(name="Basic Attention", symbol="bat", price=0.393855)
  db.session.add(bat)
  enj = Crypto(name="Enjin Coin", symbol="enj", price=0.621269)
  db.session.add(enj)
  gala = Crypto(name="Gala", symbol="gala", price=0.075518)
  db.session.add(gala)
  stx = Crypto(name="Stacks", symbol="stx", price=0.5385)
  db.session.add(stx)
  cusdt = Crypto(name="cUSDT", symbol="cusdt", price=0.0217684)
  db.session.add(cusdt)
  celo = Crypto(name="Celo", symbol="celo", price=1.26)
  db.session.add(celo)
  amp = Crypto(name="Amp", symbol="amp", price=0.01110015)
  db.session.add(amp)
  kava = Crypto(name="Kava", symbol="kava", price=2.52)
  db.session.add(kava)
  fei = Crypto(name="Fei USD", symbol="fei", price=1.001)
  db.session.add(fei)
  flex = Crypto(name="FLEX Coin", symbol="flex", price=4.95)
  db.session.add(flex)
  gno = Crypto(name="Gnosis", symbol="gno", price=188.81)
  db.session.add(gno)
  one = Crypto(name="Harmony", symbol="one", price=0.03936364)
  db.session.add(one)
  dcr = Crypto(name="Decred", symbol="dcr", price=33.81)
  db.session.add(dcr)
  cvx = Crypto(name="Convex Finance", symbol="cvx", price=7.41)
  db.session.add(cvx)
  osmo = Crypto(name="Osmosis", symbol="osmo", price=1.17)
  db.session.add(osmo)
  xaut = Crypto(name="Tether Gold", symbol="xaut", price=1847.37)
  db.session.add(xaut)
  xdc = Crypto(name="XDC Network", symbol="xdc", price=0.03733348)
  db.session.add(xdc)
  crv = Crypto(name="Curve DAO", symbol="crv", price=1.15)
  db.session.add(crv)
  xem = Crypto(name="NEM", symbol="xem", price=0.04975297)
  db.session.add(xem)
  mina = Crypto(name="Mina Protocol", symbol="mina", price=0.82647)
  db.session.add(mina)
  hot = Crypto(name="Holo", symbol="hot", price=0.00246589)
  db.session.add(hot)
  ldo = Crypto(name="Lido DAO", symbol="ldo", price=1.021)
  db.session.add(ldo)
  qtum = Crypto(name="Qtum", symbol="qtum", price=3.9)
  db.session.add(qtum)
  omi = Crypto(name="ECOMI", symbol="omi", price=0.00149961)
  db.session.add(omi)
  nxm = Crypto(name="Nexus Mutual", symbol="nxm", price=58.04)
  db.session.add(nxm)
  iost = Crypto(name="IOST", symbol="iost", price=0.01682851)
  db.session.add(iost)
  tkx = Crypto(name="Tokenize Xchange", symbol="tkx", price=4.86)
  db.session.add(tkx)
  okt = Crypto(name="OKC", symbol="okt", price=23.86)
  db.session.add(okt)
  omg = Crypto(name="OMG Network", symbol="omg", price=2.71)
  db.session.add(omg)
  comp = Crypto(name="Compound", symbol="comp", price=55.36)
  db.session.add(comp)
  btg = Crypto(name="Bitcoin Gold", symbol="btg", price=21.61)
  db.session.add(btg)
  mex = Crypto(name="Maiar DEX", symbol="mex", price=0.00007193)
  db.session.add(mex)
  mim = Crypto(name="Magic Internet Money", symbol="mim", price=0.999268)
  db.session.add(mim)
  sfm = Crypto(name="SafeMoon", symbol="sfm", price=0.00063947)
  db.session.add(sfm)
  dome = Crypto(name="Everdome", symbol="dome", price=0.01674782)
  db.session.add(dome)
  fxs = Crypto(name="Frax Share", symbol="fxs", price=6.05)
  db.session.add(fxs)
  ohm = Crypto(name="Olympus", symbol="ohm", price=17.52)
  db.session.add(ohm)
  glmr = Crypto(name="Moonbeam", symbol="glmr", price=1.28)
  db.session.add(glmr)
  kda = Crypto(name="Kadena", symbol="kda", price=1.89)
  db.session.add(kda)
  evmos = Crypto(name="Evmos", symbol="evmos", price=1.7)
  db.session.add(evmos)
  lusd = Crypto(name="Liquity USD", symbol="lusd", price=1.003)
  db.session.add(lusd)
  srm = Crypto(name="Serum", symbol="srm", price=1.029)
  db.session.add(srm)
  zrx = Crypto(name="0x", symbol="zrx", price=0.392849)
  db.session.add(zrx)
  bnt = Crypto(name="Bancor Network", symbol="bnt", price=1.32)
  db.session.add(bnt)
  iotx = Crypto(name="IoTeX", symbol="iotx", price=0.03385584)
  db.session.add(iotx)
  xido = Crypto(name="Xido Finance", symbol="xido", price=11.17)
  db.session.add(xido)
  lpt = Crypto(name="Livepeer", symbol="lpt", price=12.02)
  db.session.add(lpt)
  audio = Crypto(name="Audius", symbol="audio", price=0.427863)
  db.session.add(audio)
  ankr = Crypto(name="Ankr", symbol="ankr", price=0.03766827)
  db.session.add(ankr)
  ln = Crypto(name="LINK", symbol="ln", price=50.12)
  db.session.add(ln)
  titan = Crypto(name="TitanSwap", symbol="titan", price=3.03)
  db.session.add(titan)
  jst = Crypto(name="JUST", symbol="jst", price=0.04135786)
  db.session.add(jst)
  icx = Crypto(name="ICON", symbol="icx", price=0.383096)
  db.session.add(icx)
  glm = Crypto(name="Golem", symbol="glm", price=0.295518)
  db.session.add(glm)
  sgb = Crypto(name="Songbird", symbol="sgb", price=0.0360558)
  db.session.add(sgb)
  sushi = Crypto(name="Sushi", symbol="sushi", price=1.49)
  db.session.add(sushi)
  ens = Crypto(name="Ethereum Name Service", symbol="ens", price=11.47)
  db.session.add(ens)
  rvn = Crypto(name="Ravencoin", symbol="rvn", price=0.02690455)
  db.session.add(rvn)
  safemoon = Crypto(name="SafeMoon [OLD]", symbol="safemoon", price=1.03394e-7)
  db.session.add(safemoon)
  gusd = Crypto(name="Gemini Dollar", symbol="gusd", price=1.001)
  db.session.add(gusd)
  sc = Crypto(name="Siacoin", symbol="sc", price=0.00536279)
  db.session.add(sc)
  cel = Crypto(name="Celsius Network", symbol="cel", price=0.642604)
  db.session.add(cel)
  chsb = Crypto(name="SwissBorg", symbol="chsb", price=0.279565)
  db.session.add(chsb)
  nu = Crypto(name="NuCypher", symbol="nu", price=0.213834)
  db.session.add(nu)
  kub = Crypto(name="Bitkub Coin", symbol="kub", price=2.95)
  db.session.add(kub)
  nft = Crypto(name="APENFT", symbol="nft", price=9.4558e-7)
  db.session.add(nft)
  ont = Crypto(name="Ontology", symbol="ont", price=0.297908)
  db.session.add(ont)
  sxp = Crypto(name="SXP", symbol="sxp", price=0.535728)
  db.session.add(sxp)
  cvxcrv = Crypto(name="Convex CRV", symbol="cvxcrv", price=1.1)
  db.session.add(cvxcrv)
  rpl = Crypto(name="Rocket Pool", symbol="rpl", price=15.95)
  db.session.add(rpl)
  skl = Crypto(name="SKALE", symbol="skl", price=0.073016)
  db.session.add(skl)
  waxp = Crypto(name="WAX", symbol="waxp", price=0.123224)
  db.session.add(waxp)
  ever = Crypto(name="Everscale", symbol="ever", price=0.202496)
  db.session.add(ever)
  msol = Crypto(name="Marinade staked SOL", symbol="msol", price=41.88)
  db.session.add(msol)
  zen = Crypto(name="Horizen", symbol="zen", price=19.08)
  db.session.add(zen)
  yfi = Crypto(name="yearn.finance", symbol="yfi", price=7485.21)
  db.session.add(yfi)
  babydoge = Crypto(name="Baby Doge Coin", symbol="babydoge", price=1.471e-9)
  db.session.add(babydoge)
  elon = Crypto(name="Dogelon Mars", symbol="elon", price=4.20298e-7)
  db.session.add(elon)
  imx = Crypto(name="Immutable X", symbol="imx", price=0.980515)
  db.session.add(imx)
  rose = Crypto(name="Oasis Network", symbol="rose", price=0.065854)
  db.session.add(rose)
  poly = Crypto(name="Polymath", symbol="poly", price=0.255996)
  db.session.add(poly)
  pla = Crypto(name="PlayDapp", symbol="pla", price=0.54114)
  db.session.add(pla)
  elg = Crypto(name="Escoin", symbol="elg", price=3.37)
  db.session.add(elg)
  vgx = Crypto(name="Voyager VGX", symbol="vgx", price=0.789316)
  db.session.add(vgx)
  husd = Crypto(name="HUSD", symbol="husd", price=1.001)
  db.session.add(husd)
  scrt = Crypto(name="Secret", symbol="scrt", price=1.3)
  db.session.add(scrt)
  eurt = Crypto(name="Euro Tether", symbol="eurt", price=1.076)
  db.session.add(eurt)
  twt = Crypto(name="Trust Wallet", symbol="twt", price=0.617181)
  db.session.add(twt)
  mxc = Crypto(name="MXC", symbol="mxc", price=0.086352)
  db.session.add(mxc)
  hive = Crypto(name="Hive", symbol="hive", price=0.546079)
  db.session.add(hive)
  slp = Crypto(name="Smooth Love Potion", symbol="slp", price=0.00506649)
  db.session.add(slp)
  plex = Crypto(name="PLEX", symbol="plex", price=0.741219)
  db.session.add(plex)
  astr = Crypto(name="Astar", symbol="astr", price=0.059764)
  db.session.add(astr)
  uma = Crypto(name="UMA", symbol="uma", price=2.98)
  db.session.add(uma)
  dag = Crypto(name="Constellation", symbol="dag", price=0.077276)
  db.session.add(dag)
  renbtc = Crypto(name="renBTC", symbol="renbtc", price=29525)
  db.session.add(renbtc)
  xcm = Crypto(name="Coinmetro", symbol="xcm", price=0.648874)
  db.session.add(xcm)
  flexusd = Crypto(name="flexUSD", symbol="flexusd", price=1.001)
  db.session.add(flexusd)
  lsk = Crypto(name="Lisk", symbol="lsk", price=1.34)
  db.session.add(lsk)
  knc = Crypto(name="Kyber Network Crystal", symbol="knc", price=1.89)
  db.session.add(knc)
  dao = Crypto(name="DAO Maker", symbol="dao", price=1.96)
  db.session.add(dao)
  alusd = Crypto(name="Alchemix USD", symbol="alusd", price=0.998927)
  db.session.add(alusd)
  dgb = Crypto(name="DigiByte", symbol="dgb", price=0.01205108)
  db.session.add(dgb)
  pokt = Crypto(name="Pocket Network", symbol="pokt", price=0.16718)
  db.session.add(pokt)
  mpl = Crypto(name="Maple", symbol="mpl", price=29.35)
  db.session.add(mpl)
  juno = Crypto(name="JUNO", symbol="juno", price=3.48)
  db.session.add(juno)
  syn = Crypto(name="Synapse", symbol="syn", price=0.981858)
  db.session.add(syn)
  cspr = Crypto(name="Casper Network", symbol="cspr", price=0.03471182)
  db.session.add(cspr)
  rndr = Crypto(name="Render", symbol="rndr", price=0.691145)
  db.session.add(rndr)


  db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_crypto():
  db.session.execute('TRUNCATE crypto RESTART IDENTITY CASCADE;')
  db.session.commit()
