from app.models import db, Crypto

# prices from 06/09/2022 for defaults
# Adds a demo user, you can add other users here if you want
def seed_crypto():

  btc = Crypto(name="Bitcoin", symbol="btc", api_id="bitcoin")
  db.session.add(btc)
  eth = Crypto(name="Ethereum", symbol="eth", api_id="ethereum")
  db.session.add(eth)
  usdt = Crypto(name="Tether", symbol="usdt", api_id="tether")
  db.session.add(usdt)
  usdc = Crypto(name="USD Coin", symbol="usdc", api_id="usd-coin")
  db.session.add(usdc)
  bnb = Crypto(name="BNB", symbol="bnb", api_id="binancecoin")
  db.session.add(bnb)
  busd = Crypto(name="Binance USD", symbol="busd", api_id="binance-usd")
  db.session.add(busd)
  ada = Crypto(name="Cardano", symbol="ada", api_id="cardano")
  db.session.add(ada)
  xrp = Crypto(name="XRP", symbol="xrp", api_id="ripple")
  db.session.add(xrp)
  sol = Crypto(name="Solana", symbol="sol", api_id="solana")
  db.session.add(sol)
  doge = Crypto(name="Dogecoin", symbol="doge", api_id="dogecoin")
  db.session.add(doge)
  dot = Crypto(name="Polkadot", symbol="dot", api_id="polkadot")
  db.session.add(dot)
  wbtc = Crypto(name="Wrapped Bitcoin", symbol="wbtc", api_id="wrapped-bitcoin")
  db.session.add(wbtc)
  trx = Crypto(name="TRON", symbol="trx", api_id="tron")
  db.session.add(trx)
  dai = Crypto(name="Dai", symbol="dai", api_id="dai")
  db.session.add(dai)
  steth = Crypto(name="Lido Staked Ether", symbol="steth", api_id="staked-ether")
  db.session.add(steth)
  shib = Crypto(name="Shiba Inu", symbol="shib", api_id="shiba-inu")
  db.session.add(shib)
  leo = Crypto(name="LEO Token", symbol="leo", api_id="leo-token")
  db.session.add(leo)
  avax = Crypto(name="Avalanche", symbol="avax", api_id="avalanche-2")
  db.session.add(avax)
  ftt = Crypto(name="FTX", symbol="ftt", api_id="ftx-token")
  db.session.add(ftt)
  cro = Crypto(name="Cronos", symbol="cro", api_id="crypto-com-chain")
  db.session.add(cro)
  matic = Crypto(name="Polygon", symbol="matic", api_id="matic-network")
  db.session.add(matic)
  ltc = Crypto(name="Litecoin", symbol="ltc", api_id="litecoin")
  db.session.add(ltc)
  xcn = Crypto(name="Chain", symbol="xcn", api_id="chain-2")
  db.session.add(xcn)
  link = Crypto(name="Chainlink", symbol="link", api_id="chainlink")
  db.session.add(link)
  xlm = Crypto(name="Stellar", symbol="xlm", api_id="stellar")
  db.session.add(xlm)
  okb = Crypto(name="OKB", symbol="okb", api_id="okb")
  db.session.add(okb)
  xmr = Crypto(name="Monero", symbol="xmr", api_id="monero")
  db.session.add(xmr)
  bch = Crypto(name="Bitcoin Cash", symbol="bch", api_id="bitcoin-cash")
  db.session.add(bch)
  near = Crypto(name="NEAR Protocol", symbol="near", api_id="near")
  db.session.add(near)
  etc = Crypto(name="Ethereum Classic", symbol="etc", api_id="ethereum-classic")
  db.session.add(etc)
  algo = Crypto(name="Algorand", symbol="algo", api_id="algorand")
  db.session.add(algo)
  atom = Crypto(name="Cosmos Hub", symbol="atom", api_id="cosmos")
  db.session.add(atom)
  flow = Crypto(name="Flow", symbol="flow", api_id="flow")
  db.session.add(flow)
  uni = Crypto(name="Uniswap", symbol="uni", api_id="uniswap")
  db.session.add(uni)
  vet = Crypto(name="VeChain", symbol="vet", api_id="vechain")
  db.session.add(vet)
  tfuel = Crypto(name="Theta Fuel", symbol="tfuel", api_id="theta-fuel")
  db.session.add(tfuel)
  frax = Crypto(name="Frax", symbol="frax", api_id="frax")
  db.session.add(frax)
  xtz = Crypto(name="Tezos", symbol="xtz", api_id="tezos")
  db.session.add(xtz)
  hbar = Crypto(name="Hedera", symbol="hbar", api_id="hedera-hashgraph")
  db.session.add(hbar)
  kcs = Crypto(name="KuCoin", symbol="kcs", api_id="kucoin-shares")
  db.session.add(kcs)
  icp = Crypto(name="Internet Computer", symbol="icp", api_id="internet-computer")
  db.session.add(icp)
  fil = Crypto(name="Filecoin", symbol="fil", api_id="filecoin")
  db.session.add(fil)
  tusd = Crypto(name="TrueUSD", symbol="tusd", api_id="true-usd")
  db.session.add(tusd)
  mana = Crypto(name="Decentraland", symbol="mana", api_id="decentraland")
  db.session.add(mana)
  sand = Crypto(name="The Sandbox", symbol="sand", api_id="the-sandbox")
  db.session.add(sand)
  axs = Crypto(name="Axie Infinity", symbol="axs", api_id="axie-infinity")
  db.session.add(axs)
  ape = Crypto(name="ApeCoin", symbol="ape", api_id="apecoin")
  db.session.add(ape)
  cusdc = Crypto(name="cUSDC", symbol="cusdc", api_id="compound-usd-coin")
  db.session.add(cusdc)
  theta = Crypto(name="Theta Network", symbol="theta", api_id="theta-token")
  db.session.add(theta)
  eos = Crypto(name="EOS", symbol="eos", api_id="eos")
  db.session.add(eos)
  hbtc = Crypto(name="Huobi BTC", symbol="hbtc", api_id="huobi-btc")
  db.session.add(hbtc)
  ht = Crypto(name="Huobi", symbol="ht", api_id="huobi-token")
  db.session.add(ht)
  ceth = Crypto(name="cETH", symbol="ceth", api_id="compound-ether")
  db.session.add(ceth)
  egld = Crypto(name="Elrond", symbol="egld", api_id="elrond-erd-2")
  db.session.add(egld)
  zec = Crypto(name="Zcash", symbol="zec", api_id="zcash")
  db.session.add(zec)
  aave = Crypto(name="Aave", symbol="aave", api_id="aave")
  db.session.add(aave)
  bsv = Crypto(name="Bitcoin SV", symbol="bsv", api_id="bitcoin-cash-sv")
  db.session.add(bsv)
  usdp = Crypto(name="Pax Dollar", symbol="usdp", api_id="paxos-standard")
  db.session.add(usdp)
  dfi = Crypto(name="DeFiChain", symbol="dfi", api_id="defichain")
  db.session.add(dfi)
  btt = Crypto(name="BitTorrent", symbol="btt", api_id="bittorrent")
  db.session.add(btt)
  hnt = Crypto(name="Helium", symbol="hnt", api_id="helium")
  db.session.add(hnt)
  klay = Crypto(name="Klaytn", symbol="klay", api_id="klay-token")
  db.session.add(klay)
  grt = Crypto(name="The Graph", symbol="grt", api_id="the-graph")
  db.session.add(grt)
  neo = Crypto(name="NEO", symbol="neo", api_id="neo")
  db.session.add(neo)
  mkr = Crypto(name="Maker", symbol="mkr", api_id="maker")
  db.session.add(mkr)
  usdn = Crypto(name="Neutrino USD", symbol="usdn", api_id="neutrino")
  db.session.add(usdn)
  xec = Crypto(name="eCash", symbol="xec", api_id="ecash")
  db.session.add(xec)
  miota = Crypto(name="IOTA", symbol="miota", api_id="iota")
  db.session.add(miota)
  gt = Crypto(name="Gate", symbol="gt", api_id="gatechain-token")
  db.session.add(gt)
  usdd = Crypto(name="USDD", symbol="usdd", api_id="usdd")
  db.session.add(usdd)
  xrd = Crypto(name="Radix", symbol="xrd", api_id="radix")
  db.session.add(xrd)
  qnt = Crypto(name="Quant", symbol="qnt", api_id="quant-network")
  db.session.add(qnt)
  rune = Crypto(name="THORChain", symbol="rune", api_id="thorchain")
  db.session.add(rune)
  cdai = Crypto(name="cDAI", symbol="cdai", api_id="cdai")
  db.session.add(cdai)
  paxg = Crypto(name="PAX Gold", symbol="paxg", api_id="pax-gold")
  db.session.add(paxg)
  cake = Crypto(name="PancakeSwap", symbol="cake", api_id="pancakeswap-token")
  db.session.add(cake)
  ftm = Crypto(name="Fantom", symbol="ftm", api_id="fantom")
  db.session.add(ftm)
  waves = Crypto(name="Waves", symbol="waves", api_id="waves")
  db.session.add(waves)
  zil = Crypto(name="Zilliqa", symbol="zil", api_id="zilliqa")
  db.session.add(zil)
  nexo = Crypto(name="NEXO", symbol="nexo", api_id="nexo")
  db.session.add(nexo)
  chz = Crypto(name="Chiliz", symbol="chz", api_id="chiliz")
  db.session.add(chz)
  cusdt = Crypto(name="cUSDT", symbol="cusdt", api_id="compound-usdt")
  db.session.add(cusdt)
  lrc = Crypto(name="Loopring", symbol="lrc", api_id="loopring")
  db.session.add(lrc)
  bit = Crypto(name="BitDAO", symbol="bit", api_id="bitdao")
  db.session.add(bit)
  ar = Crypto(name="Arweave", symbol="ar", api_id="arweave")
  db.session.add(ar)
  dash = Crypto(name="Dash", symbol="dash", api_id="dash")
  db.session.add(dash)
  snx = Crypto(name="Synthetix Network", symbol="snx", api_id="havven")
  db.session.add(snx)
  flex = Crypto(name="FLEX Coin", symbol="flex", api_id="flex-coin")
  db.session.add(flex)
  amp = Crypto(name="Amp", symbol="amp", api_id="amp-token")
  db.session.add(amp)
  bat = Crypto(name="Basic Attention", symbol="bat", api_id="basic-attention-token")
  db.session.add(bat)
  enj = Crypto(name="Enjin Coin", symbol="enj", api_id="enjincoin")
  db.session.add(enj)
  ksm = Crypto(name="Kusama", symbol="ksm", api_id="kusama")
  db.session.add(ksm)
  xaut = Crypto(name="Tether Gold", symbol="xaut", api_id="tether-gold")
  db.session.add(xaut)
  fei = Crypto(name="Fei USD", symbol="fei", api_id="fei-usd")
  db.session.add(fei)
  celo = Crypto(name="Celo", symbol="celo", api_id="celo")
  db.session.add(celo)
  stx = Crypto(name="Stacks", symbol="stx", api_id="blockstack")
  db.session.add(stx)
  gala = Crypto(name="Gala", symbol="gala", api_id="gala")
  db.session.add(gala)
  dcr = Crypto(name="Decred", symbol="dcr", api_id="decred")
  db.session.add(dcr)
  xdc = Crypto(name="XDC Network", symbol="xdc", api_id="xdce-crowd-sale")
  db.session.add(xdc)
  gmt = Crypto(name="STEPN", symbol="gmt", api_id="stepn")
  db.session.add(gmt)
  kava = Crypto(name="Kava", symbol="kava", api_id="kava")
  db.session.add(kava)
  gno = Crypto(name="Gnosis", symbol="gno", api_id="gnosis")
  db.session.add(gno)
  xem = Crypto(name="NEM", symbol="xem", api_id="nem")
  db.session.add(xem)
  hot = Crypto(name="Holo", symbol="hot", api_id="holotoken")
  db.session.add(hot)
  one = Crypto(name="Harmony", symbol="one", api_id="harmony")
  db.session.add(one)
  okt = Crypto(name="OKC", symbol="okt", api_id="oec-token")
  db.session.add(okt)
  sfm = Crypto(name="SafeMoon", symbol="sfm", api_id="safemoon-2")
  db.session.add(sfm)
  osmo = Crypto(name="Osmosis", symbol="osmo", api_id="osmosis")
  db.session.add(osmo)
  mim = Crypto(name="Magic Internet Money", symbol="mim", api_id="magic-internet-money")
  db.session.add(mim)
  oneinch = Crypto(name="1inch", symbol="1inch", api_id="1inch")
  db.session.add(oneinch)
  crv = Crypto(name="Curve DAO", symbol="crv", api_id="curve-dao-token")
  db.session.add(crv)
  mina = Crypto(name="Mina Protocol", symbol="mina", api_id="mina-protocol")
  db.session.add(mina)
  iost = Crypto(name="IOST", symbol="iost", api_id="iostoken")
  db.session.add(iost)
  ldo = Crypto(name="Lido DAO", symbol="ldo", api_id="lido-dao")
  db.session.add(ldo)
  srm = Crypto(name="Serum", symbol="srm", api_id="serum")
  db.session.add(srm)
  qtum = Crypto(name="Qtum", symbol="qtum", api_id="qtum")
  db.session.add(qtum)
  tkx = Crypto(name="Tokenize Xchange", symbol="tkx", api_id="tokenize-xchange")
  db.session.add(tkx)
  omi = Crypto(name="ECOMI", symbol="omi", api_id="ecomi")
  db.session.add(omi)
  cvx = Crypto(name="Convex Finance", symbol="cvx", api_id="convex-finance")
  db.session.add(cvx)
  fxs = Crypto(name="Frax Share", symbol="fxs", api_id="frax-share")
  db.session.add(fxs)
  nxm = Crypto(name="Nexus Mutual", symbol="nxm", api_id="nxm")
  db.session.add(nxm)
  lusd = Crypto(name="Liquity USD", symbol="lusd", api_id="liquity-usd")
  db.session.add(lusd)
  btg = Crypto(name="Bitcoin Gold", symbol="btg", api_id="bitcoin-gold")
  db.session.add(btg)
  omg = Crypto(name="OMG Network", symbol="omg", api_id="omisego")
  db.session.add(omg)
  xido = Crypto(name="Xido Finance", symbol="xido", api_id="xido-finance")
  db.session.add(xido)
  ohm = Crypto(name="Olympus", symbol="ohm", api_id="olympus")
  db.session.add(ohm)
  glmr = Crypto(name="Moonbeam", symbol="glmr", api_id="moonbeam")
  db.session.add(glmr)
  comp = Crypto(name="Compound", symbol="comp", api_id="compound-governance-token")
  db.session.add(comp)
  kda = Crypto(name="Kadena", symbol="kda", api_id="kadena")
  db.session.add(kda)
  safemoon = Crypto(name="SafeMoon [OLD]", symbol="safemoon", api_id="safemoon")
  db.session.add(safemoon)
  gusd = Crypto(name="Gemini Dollar", symbol="gusd", api_id="gemini-dollar")
  db.session.add(gusd)
  titan = Crypto(name="TitanSwap", symbol="titan", api_id="titanswap")
  db.session.add(titan)
  ln = Crypto(name="LINK", symbol="ln", api_id="link")
  db.session.add(ln)
  mex = Crypto(name="Maiar DEX", symbol="mex", api_id="maiar-dex")
  db.session.add(mex)
  jst = Crypto(name="JUST", symbol="jst", api_id="just")
  db.session.add(jst)
  iotx = Crypto(name="IoTeX", symbol="iotx", api_id="iotex")
  db.session.add(iotx)
  zrx = Crypto(name="0x", symbol="zrx", api_id="0x")
  db.session.add(zrx)
  bnt = Crypto(name="Bancor Network", symbol="bnt", api_id="bancor")
  db.session.add(bnt)
  tenset = Crypto(name="Tenset", symbol="10set", api_id="tenset")
  db.session.add(tenset)
  evmos = Crypto(name="Evmos", symbol="evmos", api_id="evmos")
  db.session.add(evmos)
  lpt = Crypto(name="Livepeer", symbol="lpt", api_id="livepeer")
  db.session.add(lpt)
  ankr = Crypto(name="Ankr", symbol="ankr", api_id="ankr")
  db.session.add(ankr)
  audio = Crypto(name="Audius", symbol="audio", api_id="audius")
  db.session.add(audio)
  glm = Crypto(name="Golem", symbol="glm", api_id="golem")
  db.session.add(glm)
  kub = Crypto(name="Bitkub Coin", symbol="kub", api_id="bitkub-coin")
  db.session.add(kub)
  rvn = Crypto(name="Ravencoin", symbol="rvn", api_id="ravencoin")
  db.session.add(rvn)
  icx = Crypto(name="ICON", symbol="icx", api_id="icon")
  db.session.add(icx)
  nft = Crypto(name="APENFT", symbol="nft", api_id="apenft")
  db.session.add(nft)
  sgb = Crypto(name="Songbird", symbol="sgb", api_id="songbird")
  db.session.add(sgb)
  elg = Crypto(name="Escoin", symbol="elg", api_id="escoin-token")
  db.session.add(elg)
  husd = Crypto(name="HUSD", symbol="husd", api_id="husd")
  db.session.add(husd)
  sushi = Crypto(name="Sushi", symbol="sushi", api_id="sushi")
  db.session.add(sushi)
  eurt = Crypto(name="Euro Tether", symbol="eurt", api_id="tether-eurt")
  db.session.add(eurt)
  nu = Crypto(name="NuCypher", symbol="nu", api_id="nucypher")
  db.session.add(nu)
  ever = Crypto(name="Everscale", symbol="ever", api_id="everscale")
  db.session.add(ever)
  ens = Crypto(name="Ethereum Name Service", symbol="ens", api_id="ethereum-name-service")
  db.session.add(ens)
  chsb = Crypto(name="SwissBorg", symbol="chsb", api_id="swissborg")
  db.session.add(chsb)
  sc = Crypto(name="Siacoin", symbol="sc", api_id="siacoin")
  db.session.add(sc)
  ont = Crypto(name="Ontology", symbol="ont", api_id="ontology")
  db.session.add(ont)
  twt = Crypto(name="Trust Wallet", symbol="twt", api_id="trust-wallet-token")
  db.session.add(twt)
  cvxcrv = Crypto(name="Convex CRV", symbol="cvxcrv", api_id="convex-crv")
  db.session.add(cvxcrv)
  dome = Crypto(name="Everdome", symbol="dome", api_id="everdome")
  db.session.add(dome)
  waxp = Crypto(name="WAX", symbol="waxp", api_id="wax")
  db.session.add(waxp)
  vgx = Crypto(name="Voyager VGX", symbol="vgx", api_id="ethos")
  db.session.add(vgx)
  sxp = Crypto(name="SXP", symbol="sxp", api_id="swipe")
  db.session.add(sxp)
  yfi = Crypto(name="yearn.finance", symbol="yfi", api_id="yearn-finance")
  db.session.add(yfi)
  zen = Crypto(name="Horizen", symbol="zen", api_id="zencash")
  db.session.add(zen)
  flexusd = Crypto(name="flexUSD", symbol="flexusd", api_id="flex-usd")
  db.session.add(flexusd)
  mxc = Crypto(name="MXC", symbol="mxc", api_id="mxc")
  db.session.add(mxc)
  xcm = Crypto(name="Coinmetro", symbol="xcm", api_id="coinmetro")
  db.session.add(xcm)
  msol = Crypto(name="Marinade staked SOL", symbol="msol", api_id="msol")
  db.session.add(msol)
  plex = Crypto(name="PLEX", symbol="plex", api_id="plex")
  db.session.add(plex)
  alusd = Crypto(name="Alchemix USD", symbol="alusd", api_id="alchemix-usd")
  db.session.add(alusd)
  rose = Crypto(name="Oasis Network", symbol="rose", api_id="oasis-network")
  db.session.add(rose)
  skl = Crypto(name="SKALE", symbol="skl", api_id="skale")
  db.session.add(skl)
  babydoge = Crypto(name="Baby Doge Coin", symbol="babydoge", api_id="baby-doge-coin")
  db.session.add(babydoge)
  rpl = Crypto(name="Rocket Pool", symbol="rpl", api_id="rocket-pool")
  db.session.add(rpl)
  poly = Crypto(name="Polymath", symbol="poly", api_id="polymath")
  db.session.add(poly)
  renbtc = Crypto(name="renBTC", symbol="renbtc", api_id="renbtc")
  db.session.add(renbtc)
  elon = Crypto(name="Dogelon Mars", symbol="elon", api_id="dogelon-mars")
  db.session.add(elon)
  scrt = Crypto(name="Secret", symbol="scrt", api_id="secret")
  db.session.add(scrt)
  imx = Crypto(name="Immutable X", symbol="imx", api_id="immutable-x")
  db.session.add(imx)
  pla = Crypto(name="PlayDapp", symbol="pla", api_id="playdapp")
  db.session.add(pla)
  kunci = Crypto(name="Kunci Coin", symbol="kunci", api_id="kunci-coin")
  db.session.add(kunci)
  pokt = Crypto(name="Pocket Network", symbol="pokt", api_id="pocket-network")
  db.session.add(pokt)
  astr = Crypto(name="Astar", symbol="astr", api_id="astar")
  db.session.add(astr)
  dao = Crypto(name="DAO Maker", symbol="dao", api_id="dao-maker")
  db.session.add(dao)
  slp = Crypto(name="Smooth Love Potion", symbol="slp", api_id="smooth-love-potion")
  db.session.add(slp)
  hive = Crypto(name="Hive", symbol="hive", api_id="hive")
  db.session.add(hive)
  lsk = Crypto(name="Lisk", symbol="lsk", api_id="lisk")
  db.session.add(lsk)
  cel = Crypto(name="Celsius Network", symbol="cel", api_id="celsius-degree-token")
  db.session.add(cel)
  uma = Crypto(name="UMA", symbol="uma", api_id="uma")
  db.session.add(uma)
  dgb = Crypto(name="DigiByte", symbol="dgb", api_id="digibyte")
  db.session.add(dgb)
  dag = Crypto(name="Constellation", symbol="dag", api_id="constellation-labs")
  db.session.add(dag)
  juno = Crypto(name="JUNO", symbol="juno", api_id="juno-network")
  db.session.add(juno)
  knc = Crypto(name="Kyber Network Crystal", symbol="knc", api_id="kyber-network-crystal")
  db.session.add(knc)
  cspr = Crypto(name="Casper Network", symbol="cspr", api_id="casper-network")
  db.session.add(cspr)
  mpl = Crypto(name="Maple", symbol="mpl", api_id="maple")
  db.session.add(mpl)
  mx = Crypto(name="MX", symbol="mx", api_id="mx-token")
  db.session.add(mx)
  op = Crypto(name="Optimism", symbol="op", api_id="optimism")
  db.session.add(op)

  db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_crypto():
  db.session.execute('TRUNCATE crypto RESTART IDENTITY CASCADE;')
  db.session.commit()
